/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error": "#690005",
        "surface-dim": "#0A0A0F",
        "on-primary": "#00315d",
        "tertiary-fixed-dim": "#c0c1ff",
        "tertiary-fixed": "#e1e0ff",
        "surface-tint": "#a4c9ff",
        "on-secondary-fixed": "#00201a",
        "primary-fixed": "#d4e3ff",
        "surface-bright": "#39383e",
        "on-tertiary": "#1000a9",
        "secondary-fixed-dim": "#44ddc1",
        "on-secondary-fixed-variant": "#005145",
        "tertiary": "#c0c1ff",
        "surface": "#0A0A0F",
        "outline": "#8c919c",
        "on-tertiary-container": "#c5c5ff",
        "secondary": "#44ddc1",
        "secondary-container": "#00bea4",
        "tertiary-container": "#3f40cd",
        "surface-container-lowest": "#050505",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "on-tertiary-fixed": "#07006c",
        "surface-container-high": "#2a292f",
        "error-container": "#93000a",
        "inverse-surface": "#e4e1e9",
        "error": "#ffb4ab",
        "on-surface": "#e4e1e9",
        "secondary-fixed": "#68fadd",
        "on-primary-fixed": "#001c39",
        "outline-variant": "#424751",
        "on-primary-container": "#aaccff",
        "inverse-primary": "#1960a5",
        "surface-container-highest": "#35343a",
        "inverse-on-surface": "#303036",
        "primary-container": "#02569b",
        "on-primary-fixed-variant": "#004883",
        "on-secondary-container": "#00463b",
        "on-surface-variant": "#c2c6d2",
        "on-background": "#e4e1e9",
        "surface-container": "#1f1f25",
        "on-secondary": "#00382f",
        "on-error-container": "#ffdad6",
        "primary": "#a4c9ff",
        "surface-variant": "#35343a",
        "primary-fixed-dim": "#a4c9ff",
        "background": "#0A0A0F",
        "surface-container-low": "#1b1b20"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "section-gap-desktop": "160px",
        "margin-mobile": "20px",
        "base": "8px",
        "section-gap-mobile": "80px",
        "container-max-width": "1200px",
        "gutter": "32px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "code": ["JetBrains Mono", "monospace"],
        "display": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", { "lineHeight": "1.6", "letterSpacing": "0em", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "1.0", "letterSpacing": "0.1em", "fontWeight": "600" }],
        "code": ["14px", { "lineHeight": "1.5", "letterSpacing": "0em", "fontWeight": "450" }],
        "display": ["72px", { "lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "800" }],
        "headline-md": ["30px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "1.6", "letterSpacing": "0em", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
